### ISSUE TITLE
comparisons display `0%` instead of `100%`

### ISSUE THREAD

**Issue by peter-mouland** [Financial-Times/lantern#115]
The article metric is 0 (zero), the comparator is 443.

![screen shot 2015-10-08 at 12 58 32 pm](https://cloud.githubusercontent.com/assets/1727939/10365570/49d0a796-6dbc-11e5-8672-8bbd404c0882.png)

**Comment by radiodario** [comment]
what's the link to the article?

**Comment by radiodario** [comment]
this was fixed on #116
