### ISSUE TITLE
Map depicts Russia as wrapping around the globe, and thus next to the US

### ISSUE THREAD

**Issue by FTgremlin** [Financial-Times/lantern#168]
### Priority
Trivial

### Steps to Reproduce
1, Go to: http://lantern.ft.com/articles/34a35722-71ec-11e5-ad6d-f4ed76f0900a/section/Pink%20Snow:%20Ski%20Special
2, Scroll down to Global-Reach map

### Expected Results
Russia should be on the right, US on the left

### Actual Results
Russian wraps around to the other side
![screen shot 2015-10-28 at 13 50 00](https://cloud.githubusercontent.com/assets/12858421/10790483/77909abe-7d7b-11e5-8a61-a9758961b0ec.png)

### Notes
None

**Comment by radiodario** [comment]
ಠ_ಠ

in all seriousness i think we should change the projection to something non-mercator, but that tip of russia is on the {-180, 0] interval of latitudes!

**Comment by FTgremlin** [comment]
Relevant: https://www.youtube.com/watch?v=OH1bZ0F3zVU

I guess it's not *actually a bug* but personal preference. Happy to close this if we don't agree.

**Comment by FTgremlin** [comment]
The powers that be have declared that this is not a bug. :( :-1:
