### ISSUE TITLE
handle google auth errors

### ISSUE THREAD

**Issue by peter-mouland** [Financial-Times/lantern#41]
* [x] `Forbidden` e.g. when you click your non-ft email account to login with
    * Hitting refresh will then cause the following error
* [x] `Invalid code` (e.g. trying to hack the auth callback or a timedout code) 
   * i.e. [example out of date url](http://localhost:3000/auth/google/callback?code=4/vjkMMxKDENAea882FWK1e5oqDl6JCjqMB782V0MKc1I)

Now:
 * [ ] logging in with non-ft account causes redirect to 'loging fail, try again?' forever

**Comment by FTgremlin** [comment]
Moved to Trello.
