### ISSUE TITLE
Extended charts crush text on the axis

### ISSUE THREAD

**Issue by FTgremlin** [Financial-Times/lantern#83]
### Priority
Low

### Steps to Reproduce
Check out the link provided

### Expected Results
Chart should adapt text to always fit

### Actual Results
https://lantern.ft.com/articles/4b2ce740-47e1-11e5-b3b2-1672f710807b

### Notes
n/a

**Comment by radiodario** [comment]
can you provide a screenshot or close this? it seems to be fine to me?

**Comment by peter-mouland** [comment]
now the times have been removed, the issue has been fixed
